# SQL Manager Lite for MySQL 5.3.1.7
# ---------------------------------------
# Host     : localhost
# Port     : 3306
# Database : acadsystem


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES latin1 */;

SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE `acadsystem`
    CHARACTER SET 'utf8'
    COLLATE 'utf8_general_ci';

USE `acadsystem`;

#
# Structure for the `tbcadcli` table : 
#

CREATE TABLE `tbcadcli` (
  `ID` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(20) COLLATE utf8_general_ci NOT NULL,
  `CPF` INTEGER(11) NOT NULL,
  `RG` INTEGER(11) NOT NULL,
  `ENDERECO` VARCHAR(20) COLLATE utf8_general_ci NOT NULL,
  `TELEFONE` INTEGER(11) DEFAULT NULL,
  PRIMARY KEY USING BTREE (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=1 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='InnoDB free: 4096 kB';

#
# Structure for the `tbpagamento` table : 
#

CREATE TABLE `tbpagamento` (
  `ID` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) COLLATE utf8_general_ci NOT NULL,
  `PAG_ANTERIOR` INTEGER(11) DEFAULT NULL,
  `VALOR` INTEGER(11) NOT NULL,
  `DATA_PAGAMENTO` INTEGER(11) NOT NULL,
  PRIMARY KEY USING BTREE (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=1 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='InnoDB free: 4096 kB';



/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;